export const GET_LIST = 'GET_LIST'
export const SET_LIST = 'SET_LIST'

export const GET_LIST_FAILED = 'GET_LIST_FAILED'
export const GET_CURRENT_RANKING_FAILED = 'GET_CURRENT_RANKING_FAILED'

export const GET_CURRENT_RANKING = 'GET_CURRENT_RANKING'
export const SET_CURRENT_RANKING = 'SET_CURRENT_RANKING'

export const GET_RANKING = 'GET_RANKING'

export const GET_RANKING_DONE = 'GET_RANKING_DONE'
export const GET_RANKING_FAILED = 'GET_RANKING_FAILED'
