export const FETCH_PROFILE_REQUEST = 'FETCH_PROFILE_REQUEST'
export const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS'
export const FETCH_PROFILE_ERROR = 'FETCH_PROFILE_ERROR'

export const FETCH_USER_HISTORIC = 'FETCH_USER_HISTORIC'
export const FETCH_USER_HISTORIC_SUCCESS = 'FETCH_USER_HISTORIC_SUCCESS'
export const FETCH_USER_HISTORIC_FAIL = 'FETCH_USER_HISTORIC_FAIL'

export const FETCH_USER = 'FETCH_USER'
export const FETCH_USER_DONE = 'FETCH_USER_DONE'
export const FETCH_USER_FAIL = 'FETCH_USER_FAIL'

export const UPDATE_USER_MARKETING = 'UPDATE_USER_MARKETING'
export const UPDATE_USER_MARKETING_DONE = 'UPDATE_USER_MARKETING_DONE'
export const UPDATE_USER_MARKETING_FAIL = 'UPDATE_USER_MARKETING_FAIL'
