export const REQUEST_UPLOAD_COUPON = 'REQUEST_UPLOAD_COUPON'
export const SUCCESS_UPLOAD_COUPON = 'SUCCESS_UPLOAD_COUPON'
export const FAIL_UPLOAD_COUPON = 'FAIL_UPLOAD_COUPON'
export const CLEAN_UPLOAD_COUPON = 'CLEAN_UPLOAD_COUPON'

export const GET_ALL_STORES = 'GET_ALL_STORES'
export const SET_ALL_STORES = 'SET_ALL_STORES'
